TST Unpin build_stack
rapidsai/integration pull request #199
Opened 2020-12-14 23:09 UTC by mike-wendt

Run tests to check stability of build stack with allowing gcc 9.3 built packages from conda-forge

2020-12-14 23:09 UTC, mike-wendt commented
Wait for test result review to determine if this should be merged

2020-12-15 15:41 UTC, ajschmidt8 requested changes
rejecting these changes to remove this PR from our daily reminders.

2020-12-15 21:05 UTC, mike-wendt commented
@jakirkham @kkraus14 any objections or concerns? I don't think we'll face the same issues we had with 7.3 -> 7.5 so this should be fine and builds fine

2020-12-15 22:27 UTC, jakirkham approved these changes

2020-12-15 22:36 UTC, ajschmidt8 approved these changes

2020-12-15 22:36 UTC, merged