Upgrade to Treelite 1.0.0 stable
rapidsai/integration pull request #210
Opened 2021-01-21 14:14 UTC by hcho3

The 1.0.0 stable version of Treelite is [virtually identical to the 1.0.0 RC1 version](https://github.com/dmlc/treelite/pull/246), so I don't expect any code to break.

2021-01-21 16:21 UTC, ajschmidt8 approved these changes

2021-01-21 16:36 UTC, ajschmidt8 requested changes
blocking this until the new `treelite` version is tested in `cuml`. See below comment for details.

https://github.com/rapidsai/cuml/pull/3394#issuecomment-764775212

2021-01-23 01:13 UTC, hcho3 commented
Can we merge this, now that https://github.com/rapidsai/cuml/pull/3394 is passing the test with the latest Treelite?

2021-01-25 20:27 UTC, ajschmidt8 approved these changes

2021-01-25 20:27 UTC, merged

2021-01-25 20:27 UTC, ajschmidt8 commented
@hcho3, done!